### ISSUE TITLE
Player hangs at startup and won't load.

### ISSUE THREAD

**Issue by gh0stisic** [kbhomes/radiant-player-mac#237]
When I open the player it hangs on a white screen, nothing is displayed, no errors are given. The player fails to load. Please see screenshot below. 
![radiantplayerscreenshotblank](https://cloud.githubusercontent.com/assets/9011344/4528175/bded3f02-4d6c-11e4-9bff-14f0ee908e68.png)

**Comment by lwasyl** [comment]
Same here - at first application loaded correctly, but instructed me to install adobe flash player. During downloading my internet connection dropped, I had to force quit Radiant Player. Then it wouldn't start again

There seems to be an issue with downloading adobe from Safari, as it hanged while downloading Flash outside of Radiant Player as well.

Downloading Flash Player via Chrome and installing it + clearing cookies in Radiant Player fixed the issue

**Comment by kbhomes** [comment]
This issue would have been fixed with #258, I believe.

**Comment by gh0stisic** [comment]
@kbhomes Correct. Thank you.

**Comment by presto211** [comment]
I'm still getting a basically blank screen, even after updating Flash and reinstalling Radiant Player (I love this app, btw). I'm running Mac OS 10.8.5. Here's a screenshot as my player isn't *completely* blank, just for reference…Thanks!

![screen shot 2015-03-20 at 12 17 26 pm](https://cloud.githubusercontent.com/assets/11575269/6755744/afe5e6fa-cefb-11e4-9540-5e1380f45c36.jpg)
