### ISSUE TITLE
Google Re-Design = Fubar'd UI

### ISSUE THREAD

**Issue by tonybaroneee** [kbhomes/radiant-player-mac#318]
:(

![screen shot 2015-05-14 at 1 14 34 pm](https://cloud.githubusercontent.com/assets/844249/7637337/2d5e6e9e-fa3b-11e4-89ac-af874db1fd5c.png)

**Comment by breakingco** [comment]
can confirm. Can't use app at all. the square overlaying the bottom left hand corner appears to be Flash messing up, though in this case, updating it has no effect.

**Comment by ShutterMunster** [comment]
Was just coming to post about this. Blows.

**Comment by sangyye** [comment]
can also confirm, app is not working anymore. The redesign of google music broke it completely.

**Comment by chasewarner** [comment]
Also confirmed. Just downloaded it and am seeing the exact same issue on OS X 10.10.3

**Comment by rockymountainhigh1943** [comment]
Also confirmed.. I use this everyday so thank you for your work on this! Can we get an update? :-)

**Comment by UnicornDelight** [comment]
I use this everyday and haven't looked into the code before. I dug in quickly to the design and have a quick fix for the navigation, not the playback. I'll try to help with the playback issues as much as I can since I freaking love this player, but not sure what I can do quickly as I am not familiar with how it was written.

UI NAVIGATION Quick Fix: https://gist.github.com/UnicornDelight/79b4c9bee71b9397b9cb

In addition, can we all confirm the exact issues people are having with playback? Want to see if anything varies.

**Comment by shawn-mitch** [comment]
@UnicornDelight For me, the songs just don't load. I can get to a playlist and launch a song, but it just spins and never starts.

**Comment by rockymountainhigh1943** [comment]
Same for me ^

**Comment by niccol** [comment]
I'm running into the same issue as Shawn on OS X 10.10.3

**Comment by bondt** [comment]
UI is a bit messy, but songs and navigation work fine for me.

**Comment by jrmehle** [comment]
On 10.10.3 and while the UI is a bit clunky, selecting and playing music works fine.

**Comment by afunix** [comment]
OS X 10.9.5
Flash Player 17.0.0.188
Radiant 1.3.3

White box (flash) is at the bottom of the screen. Music is not being played...

**Comment by hashneo** [comment]
Same issues

**Comment by ewa4618** [comment]
1. Access Google Play Music with using web browser
2. Go to Settings > Labs
3. Turn "HTML 5 Audio" ON
4. Run Radiant Player, and you should be able to load/play songs

**Comment by twolfson** [comment]
I have written an Electron wrapper around Google Music with media key bindings that supports this latest Google Music redesign. It is not as fully featured as Radiant but it does work.

https://github.com/twolfson/google-music-electron

**Comment by afunix** [comment]
ewa4618, this option does not help me.. Radiant still shows white box and does nothing upon pressing Play button..

**Comment by shakeelmohamed** [comment]
+1

**Comment by hutchy2570** [comment]
If you just need global media keys, then I've just updated my fork of Google Music Keys to handle the new UI.

It works for me as a stopgap until Radiant Player is updated.

https://github.com/hutchy2570/GoogleMusicKeys/releases/tag/2015-05-18

**Comment by jawtab** [comment]
hutchy2570 is a genius!  

Does it work with fluid?  http://fluidapp.com

**Comment by jawtab** [comment]
FLUID app behaves exactly like Radiant Player. and no go with hutchy's MUSIC KEYS.  :(

**Comment by hutchy2570** [comment]
Google Music Keys (and my fork) simply iterate over all open tabs in Chrome and Safari until they find one with Google Play Music in the title, then they fire the js at the page to press the button.  It's enough for me as a workaround until Radiant Player (or Webgtk+/Google Music) is updated

**Comment by jrmehle** [comment]
Another bug I've found is that last.fm integration seems broken now. Don't see an icon in the UI at all now and it doesn't seem to be scrobbling.

**Comment by shawn-mitch** [comment]
A stopgap until it's fixed is using Google's Google Play Music extension or the Key Socket Media Keys extension for Chrome. Both allow you to use media keys in the browser and the GPM extension has a mini player, though it's not attached to the menu bar like the Radiant one.

**Comment by mfkp** [comment]
Thanks @shawn-mitch, the Key Socket Media Keys extension is working well for me.

Link for the lazy: https://chrome.google.com/webstore/detail/key-socket-media-keys/fphfgdknbpakeedbaenojjdcdoajihik?hl=en

**Comment by kbhomes** [comment]
Currently looking into this! UI has been taken care of, but this pesky Flash Player issue is stopping this dead in its tracks. I'll continue to research this problem, rest assured!

**Comment by mfkp** [comment]
Thanks for the update @kbhomes, :+1: 

Excuse my ignorance, but what's the reason flash is even needed? Shouldn't it be possible to go full HTML5 audio?

**Comment by twolfson** [comment]
@kbholmes As a heads up Flash might be a red herring. I had a similar problem in `google-music-webkit` on nw.js but had to add an MPEG codec which got things working

[https://github.com/nwjs/nw.js/wiki/Using-MP3-&-MP4-(H.264)-using-the--video--&--audio--tags.](https://github.com/nwjs/nw.js/wiki/Using-MP3-&-MP4-(H.264)-using-the--video--&--audio--tags.)

**Comment by plauclair** [comment]
@kbhomes, might it be that it's looking for a known to be supported user agent and falling back to flash? I don't know much about how the wrapper works, hopefully there is a way to spoof the UA? I know if I spoof the UA in Safari to weird values, Google Music will behave weirdly.. Thinking this might be related. Good luck! :+1:

**Comment by fenryxo** [comment]
Hello. I'm a developer of Nuvola Player, which has similar issue like Radiant Player (tiliado/nuvolaplayer#100). Regarding to HTML5 playback, [Google Play Music requires Media Source Extension with MP3 support](https://bugzilla.mozilla.org/show_bug.cgi?id=911837#c37), roughly:

* `new window.Audio("").canPlayType('audio/mpeg') === 'probably'`
* `window.MediaSource.isTypeSupported('audio/mpeg') === true`

**Comment by kbhomes** [comment]
[And the beta is out!](https://github.com/kbhomes/radiant-player-mac/releases/tag/v1.3.3.1-beta)

Everybody who would like to, please try this out, it should fix the main issues we're seeing. I still haven't gotten myself access to a 10.9 or 10.8 machine, unfortunately :disappointed:, so any feedback on those platforms would be greatly appreciated.

Hopefully the update will be available to all users by tomorrow.

**Comment by kbhomes** [comment]
@twolfson, @fenryxo: Thanks for the information, guys. I'll try to look into how to include the MPEG audio support with Cocoa WebViews. In the meanwhile, the way I fixed the Flash issue was to dig into the Polymer source, where I found that there was a discrepancy/bug that appears in Cocoa WebViews but *not* in Safari. More information here: 7cbdb201621eff0fec98557f62d3d2348cf0f78f

**Comment by mfkp** [comment]
Hey @kbhomes, thanks for working on this and getting the beta out there! Unfortunately playback still isn't working for me (I'm on 10.9.5)

It looks like the track is loading and it appears to be playing (time indicator is increasing, but play button is not indicating it's playing), but the volume is muted and it won't let me increase it.

Here's a gif of what i'm talking about:
![radiant-player-beta](https://cloud.githubusercontent.com/assets/67730/7738873/3b7f7162-ff0e-11e4-9270-a266dc312ef8.gif)

**Comment by jtharpla** [comment]
Just installed the new beta on 10.10.3 and everything is working great here -- currently listening to "Riding with the King" (RIP B.B.)  --  I had previously enabled HTML5 audio in the Labs section of Google Music, so maybe give that a try, seems to work fine with Radiant

**Comment by mfkp** [comment]
I also had HTML5 audio, and no dice. Switched it back to flash to see if that helped, but same behavior there.

**Comment by shakeelmohamed** [comment]
Luckily for me, I have a super-cached version on my work laptop so this isn't bugging me too much (humble brag)

**Comment by hashneo** [comment]
Works for me on 10.0.3 with HTML 5 and Flash.

**Comment by ewa4618** [comment]
Works on 10.10.4 public beta, both Flash and HTML 5 (though I had to turn it off and then on again).

**Comment by tonybaroneee** [comment]
@kbhomes Great job and thanks for the quick turn-around!

**Comment by plauclair** [comment]
Works great on latest 10.10.4! :+1: Enjoy the donation! 😄

**Comment by kbhomes** [comment]
Great to hear that it's working on Yosemite. And thank you @plauclair and everyone else! :smile:

@mfkp: Okay, so I've gotten access to my 10.9.4 system and the beta appears to be working, certain UI issues aside. The playback is working fine for me. 

Can you help me troubleshoot? Open up the beta and try to play a song. When it doesn't work, right click on the Search bar and click `Inspect Element`. The inspector should pop up, click on `Console`, and select all and copy all the console output and paste it into a Gist. Hopefully that will be enough to figure out what's going on!

**Comment by shakeelmohamed** [comment]
@kbhomes I'm my home machine is 10.9.5, just updated to the beta and it works for the most part. The hamburger menu is hit & miss, the queue button doesn't work, and it's generally slower than in the browser. Otherwise it's great thanks for the fix! :+1:

**Comment by kbhomes** [comment]
@shakeelmohamed Hmm, looks like you're right re: the queue button, that is a problem that I'm encountering in Safari as well, as well as the other general UI quirks like scrollbars, incorrect behavior in Polymer (UI library) components, and others. 

According to [Polymer's compatibility table/statement][1], only Safari 8+ is officially supported. Since I believe the version of WebKit that is used by Cocoa is built into the system version, I think the unfortunate implication is that these UI faults are unavoidable on version of Mac OS X before 10.10. :cry: 

[1]: https://www.polymer-project.org/0.5/resources/compatibility.html

**Comment by sangyye** [comment]
@kbhomes the beta works nice, set aside some ui glitches (i use google music in german, so some text are longer than in english, i think) But I have to manual Download the Beta. I switch in the App to the Beta Channel, check for updates, It shows me there are updates and offers me a download now. And if I click it the only think happened is that the homepage opened in chrome. Is that the wanted behavior?

**Comment by kbhomes** [comment]
@sangyye Ah, good call! I never updated the home page to reflect the release of a beta version. I should make sure to remember that from now on.

**Comment by fenryxo** [comment]
@kbhomes: Thanks for sharing the Polymer fix. Have you reported to Polymer's bug tracker?

**Comment by hutchy2570** [comment]
@kbhomes Works great for me on 10.10.3. Thanks!

**Comment by mfkp** [comment]
@kbhomes when I right-click on the search bar I see this: http://puu.sh/hV4K8/3311ad9753.png

when I right-click anywhere else, it's this: http://puu.sh/hV4LY/39822882b4.png

Anything special I need to do to enable the inspector?

**Comment by kbhomes** [comment]
@mfkp Oh sorry, I meant to include these instructions but forgot. In Terminal, run `defaults write NSGlobalDomain WebKitDeveloperExtras -bool true`, restart the app, and it should be available.

**Comment by mfkp** [comment]
@kbhomes that's the trick.

Here's the console log: https://gist.github.com/mfkp/c29529f5101df1c29e58

**Comment by mfkp** [comment]
Update: this is really weird, but I disconnected from my VPN, reloaded everything, and now it seems to be working.

I did get this error, but I'm not sure it's affecting anything:
```
[Error] ReferenceError: Can't find variable: MusicAPI
	global code (listen, line 1)
```

Anyway, thanks for getting this update out. I just threw a few more dollars in your tip jar.

**Comment by mfkp** [comment]
:moneybag: [Donation link for the lazy](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=sajidanwar94@gmail.com&lc=US&item_name=Radiant%20Player) :moneybag:

**Comment by dlhextall** [comment]
The new beta fixed it for me (10.10.3)!

**Comment by jefforshalick** [comment]
Thanks for working on this @kbhomes! Like some others said, some UI glitches in the beta but it works for me now! Looking forward to the new release. And here's some buckeroonies in your tip jar!

**Comment by seanlmoody** [comment]
I'm using v1.3.3.1-beta on OS 10.10.3 and I'm having issues with the menu/side bar on the welcome/listen now page. When I click the three bars menu button, the side menu slides out then stays there and freezes up the app entirely (with the exception on the media buttons, oddly). The content on that page also doesn't resize to include the width of the sidebar like it normally does, the side bar just covers anything on the far left side of the app window.

![screen shot 2015-05-21 at 10 34 49](https://cloud.githubusercontent.com/assets/12548856/7755140/ee25a50a-ffa6-11e4-80f1-0d65070de43e.png)

If I start the app and click on an album or an artist (anything that takes me to a new full page) then I can click on the menu bars button and the side bar will slide out and everything on the page will resize like it's meant to. But if I click on listen now and go back to that page and try to click the menu button again it freezes up.

![screen shot 2015-05-21 at 10 40 36](https://cloud.githubusercontent.com/assets/12548856/7755142/effb776a-ffa6-11e4-8312-88343a91c103.png)

The app is fantastic otherwise, thank you!

**Comment by kbhomes** [comment]
Thank you all so much for the support!

@seanlmoody That's very strange, can you let me know if this issue exists when you open Google Play Music in Safari?

**Comment by kbhomes** [comment]
@fenryxo I hopped over to your repository and saw that the Web Components fix worked for you as well, which is good to hear. I haven't yet reported this to @webcomponents because I was trying to investigate further/determine how to show a reproducible bug report for this (and haven't had much experience writing any reports). Were you planning on submitting an issue with them?

**Comment by fenryxo** [comment]
@kbhomes I've already reported it as webcomponents/webcomponentsjs#308, but I'm sure the bug report needs some refinement from you as I don't know much about the JavaScript prototype stuff.

**Comment by nashbridges** [comment]
1.3.3.1-beta, 10.9.5

Mini player (with full cover) is updated only when main window is active

**Comment by kylebcooke** [comment]
1.3.3.1-beta worked for me thanks @kbhomes !

**Comment by seanlmoody** [comment]
@kbhomes it's been working for me fine in safari. 

When I came back to try out Radiant this morning, it actually didn't freeze up right away and will work for a minute or two and the get frozen up again. But I'm actually able to open the app at this point and go straight to the side menu and open and close it a couple times and play music.

This is problem that I'm seeing the most now; page contents shrunk down the side as though the side bar is still out, three bar menu icon is gone, arrows are too far over and the listen now text is over the search box. When it gets to this point it's frozen and I have to force quit, but the music still continues playing.

![screen shot 2015-05-22 at 11 38 16](https://cloud.githubusercontent.com/assets/12548856/7777624/6e8dce52-0079-11e5-9939-60de0e2bf07b.png)

**Comment by jjanusch** [comment]
This appears to still be an issue in 1.3.3.2-beta. There is a white Flash element covering the bottom left corner and no songs will play. This happens with HTML5 Audio turned on and off. I'm running 10.10.3

**Comment by kbhomes** [comment]
@jjanusch Do you have the latest version of Flash Player in Safari? Is the white box + no playing the only issue or are the navigation menu and traffic light buttons also broken?

**Comment by jjanusch** [comment]
@kbhomes Updating the version of Flash removed the white box (it appears during the loading screen but is gone by the time the interface loads). To get music to start playing, I had to disable HTML5 audio but only certain songs play. 

I did notice something peculiar, though. The songs that do not play all seem to be tracks I uploaded myself. Tracks sourced from Google all seem to play.

**Comment by afunix** [comment]
Neither 1.3.3.1, nor 1.3.3.2 shows play queue.
When I press queue button Radiant draws white vertical line and white triangle right near the button.

**Comment by kbhomes** [comment]
@afunix: I suspect you are on Mac OS X 10.9. If you are, can you jump over to #323, comment and let me know whether the queue button is working properly in Safari?

**Comment by kbhomes** [comment]
@jjanusch So enabling HTML5 audio in the settings actually prevented music from playing? Would you happen to know the file format of the songs that you uploaded?

**Comment by jjanusch** [comment]
@kbhomes I just tested again and HTML5 audio is working for tracks I didn't upload. I must not have realized I was doing it with those tracks.

The tracks I uploaded would be mostly MP3s with the occasional M4A from iTunes.

**Comment by kbhomes** [comment]
@jjanusch I unfortunately can't seem to replicate your issue with my own uploaded songs, typically MP3s. Can you confirm that they do work in Safari?

**Comment by jjanusch** [comment]
@kbhomes I did some testing and it looks like this is a problem with the tracks themselves. I downloaded one of the tracks and tried playing it in Safari and it was corrupted. 3 seconds of garbled sound. It won't play via Google Music at all in Safari. I can play the same track in Chrome just fine, though. 

I think this is on me, not you. I'll either have to figure out what is wrong with these songs (it doesn't appear to be every song, just a portion of the ones I uploaded) and/or re-upload them or just stick with using Chrome (which I think is what I will do, honestly).

Sorry about this. It hadn't even occurred to me that it could be something to do with the songs I uploaded and just figured it was a permissions issue.
